version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        USERNAME: ${DEV_USER:-developer}
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    ports:
      - "3000:3000"
    user: ${DEV_USER:-developer}
    working_dir: /workspace
    environment:
      BUNDLE_PATH: vendor/bundle
      ELASTICSEARCH_URL: http://elasticsearch:9200
      PGHOST: db
      PGUSER: postgres
      PGPASSWORD: postgres

  db:
    image: postgres:9
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./create-db-user.sql:/docker-entrypoint-initdb.d/create-db-user.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
        # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
        # (Adding the "ports" property to this file will not forward from a Codespace.)

  elasticsearch:
    image: elasticsearch:1.5.2
    restart: unless-stopped
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

volumes:
  postgres-data:
  elasticsearch-data:
  devcache:
